### ISSUE TITLE
Does not translate image added in clipboard

### ISSUE THREAD

**Issue by guypsia** [LyreneLiu/auto-paste-picture-to-google-translate#1]
Hello Liu. 

Thanks for response but the sample Auto-Paste-Picture-In-Google-Translate does not work. 

After download, and modify label (and adding alert message for check if function is call)

function pastePic() {
    alert("Copy");
	document.querySelector('[aria-label="Coller une image depuis le presse-papiers"]').click();
}

I add extension : 
> when added, the google translate image page is automaticaly opened and activated. 
So i open in new tab a sample image web page [m.media-amazon.com/images/I/…](https://m.media-amazon.com/images/I/81z13uApmlL._AC_UF894,1000_QL80_.jpg) and i copy it in clipboard (ctrl-c or click copy)  but nothing happens ?
> i try also to copy (ctrl-c) picture from clipboard windows history and nothing happens too ?

Thanks for help

**Comment by LyreneLiu** [comment]
It didn't support window of Google Translate different from that of picture tab in the first version. I've done this support in the commit: [13da9a25ce05de9e3ad1ed8661905a47f3d7146d](https://github.com/LyreneLiu/auto-paste-picture-to-google-translate/tree/13da9a25ce05de9e3ad1ed8661905a47f3d7146d).
